### ISSUE TITLE
AppleTV with no authentication key, create one using '-l' option

### ISSUE THREAD

**Issue by NGDM** [GioF71/spotconnect-docker#1]
I'm getting this message in the logs:
`[08:56:34.543] AddRaopDevice:523 [0x64cf00]: AppleTV with no authentication key, create one using '-l' option`

Could you explain what the added value is of creating this authentication key? 
Should I do this?

**Comment by GioF71** [comment]
Hello, I cannot answer you, I am not the author of SpotConnect. My project is a docker image for spotConnect. Maybe try opening an issue [here](https://github.com/philippe44/SpotConnect).
Thank you

**Comment by NGDM** [comment]
Thanks for the help!
Just tried, got the PIN code and registered it, but playing Spotify to the Apple TV still fails.
I'll need to submit an issue with the project owner.

**Comment by GioF71** [comment]
Hello, can we close this?
Of course if there is need of changes in the image in order to support the feature, you can create a new ticket.
Cheers

**Comment by NGDM** [comment]
Sure thing, this issue can be closed. I'll create a new ticket once I'll recreate the issue and log it with the orginal project. 
Thanks for your support
